I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/gameplay/global_variables.rpy", line 1, in script
    init -1 python:
  File "game/gameplay/global_variables.rpy", line 11, in <module>
    place_1,place_2,place_3,place_4,place_5,place_6,place_7,
NameError: name 'place_1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/gameplay/global_variables.rpy", line 1, in script
    init -1 python:
  File "C:\Users\Michael\Desktop\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Michael\Desktop\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/gameplay/global_variables.rpy", line 11, in <module>
    place_1,place_2,place_3,place_4,place_5,place_6,place_7,
NameError: name 'place_1' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
 
Sat Sep 26 23:23:54 2020
